name: Vprofile CICD Workflow

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test

  Deploy_To_DockerHub:
    runs-on: ubuntu-latest
    needs: Testing
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: vprofile-app
          path: target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mataz1996
          password: dckr_pat_U0RSrxSqDXGsqHC7kWev0_5RcB0

      - name: Build and push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker-files/app/Dockerfile
          push: true
          tags: mataz1996/vprofileapp:latest

  Local_Deploy_To_Laptop:
    runs-on: self-hosted
    needs: Deploy_To_DockerHub
    steps:
      - name: Stop and remove old container if exists
        run: |
          docker stop vprofile-prod || true
          docker rm vprofile-prod || true

      - name: Pull latest image from Docker Hub
        run: docker pull mataz1996/vprofileapp:latest

      - name: Run new container on Laptop
        run: docker run -d -p 8080:8080 --name vprofile-prod mataz1996/vprofileapp:latest