name: vProfile CICD Workflow

# هنا نحدد المحفزات (Triggers)
on:
  # 1. تفعيل محفز طلب السحب تجاه فرع main
  pull_request:
    branches:
      - main

  # 2. تفعيل زر التشغيل اليدوي في واجهة جيت هاب
  workflow_dispatch: 

jobs:
  # هنا تضع الوظائف والخطوات الخاصة بك (مثل بناء الكود أو الفحص)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5